name: CI

on:
  create:
    tags:
      - v*
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    env:
      SOLUTION: "TypeContractor.sln"
      DOTNET_CLI_TELEMETRY_OPTOUT: true

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Get Build Version
        run: |
          Import-Module .\build\GetBuildVersion.psm1
          Write-Host $Env:GITHUB_REF
          $version = GetBuildVersion -VersionString $Env:GITHUB_REF
          Write-Host "Build version: $version"
          echo "BUILD_VERSION=$version" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
        shell: pwsh

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            9.0.x

      - name: Display dotnet version
        run: dotnet --version

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build $SOLUTION --configuration Release -p:Version=$BUILD_VERSION --no-restore

      - name: Run tests
        run: dotnet test /p:Configuration=Release --no-restore --verbosity normal

      - name: Publish
        if: startsWith(github.ref, 'refs/tags/v')
        run: dotnet nuget push **\TypeContractor.$BUILD_VERSION.nupkg -s 'https://api.nuget.org/v3/index.json' --api-key ${{secrets.NUGET_API_KEY}}
